M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Thu 08 Sep 2022 10:16:42 PM MST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-08T22:16:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X5.75Y-4.05
X5.75Y-5.54
T0
M30
